
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold Italic"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font.normal]
family = "Iosevka NF"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/gruvbox_dark.toml"
]
