import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml",
  # "~/.config/alacritty/catppuccin-frappe.toml",
   "~/.config/alacritty/catppuccin-macchiato.toml",
  # "~/.config/alacritty/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold Italic"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font.normal]
family = "Iosevka NF"
style = "Regular"
